MODULE htgs
$$ DATA, 1
$^   AcnumChanged, 1, SEV_ERROR
Please make sure to include the original accession number when
making the update of your record. This record was not updated 
in the database, and we await for the correct resubmission of
this record before we can process this update.

$^   SeqNameChanged, 2, SEV_ERROR
Please make sure to include the original seqname/clone_name
when making the update of your record. This record was not updated 
in the database, and we await for the correct resubmission of
this record before we can process this update. If you real need to
change the seqname/clone_name, please send an email request
to htgs@ncbi.nlm.nih.gov.

$^   WithdrawnEntry, 3, SEV_ERROR

$^   SecondaryAcnum, 4, SEV_ERROR

