MODULE toasn3
$$ ORGANISM, 1
$^   Empty, 1, SEV_WARNING
$^   NotFound, 2, SEV_WARNING
$^   Diff, 3, SEV_WARNING
$$ SOURCE, 2
$^   MultipleQualifiers, 1, SEV_WARNING
$^   DiffQualifiers, 2, SEV_WARNING
$^   Identical, 3, SEV_WARNING
$^   NotFound, 4, SEV_WARNING
$^   GeneticCode, 5, SEV_WARNING
$^   UnwantedQualifiers, 6, SEV_WARNING
$^   MissingOrganism, 7, SEV_WARNING
$^   NotFoundWHole, 9, SEV_WARNING
$^   Multiple, 10, SEV_WARNING
$^   Diff, 11, SEV_WARNING
$^   QualDiffValues, 12, SEV_WARNING
$^   IllegalQual, 13, SEV_WARNING
$^   QualUnknown, 14, SEV_INFO
$$ TAXONOMY, 4
$^   GeneticCode, 1, SEV_ERROR
$$ FEATURE, 5
$^   CannotMapDnaLocToAALoc, 1, SEV_ERROR
$^   BadLocation, 2, SEV_WARNING
$^   CDSNotFound, 3, SEV_WARNING
