MODULE validatr

$$ FEATURE, 1
$^   UnknownFeatureKey, 1, SEV_WARNING
$^   MissManQual, 2, SEV_WARNING
Mandatory qualifier missing.
$^   QualWrongThisFeat, 3, SEV_WARNING
$^   FeatureKeyReplaced, 4, SEV_WARNING
$^   LocationParsing, 5, SEV_ERROR
$^   IllegalFormat, 6, SEV_ERROR
$$ QUALIFIER, 2
$^   InvalidDataFormat, 1, SEV_WARNING
$^   Too_many_tokens, 2, SEV_WARNING
$^   MultiValue, 3, SEV_WARNING
$^   UnknownSpelling, 4, SEV_WARNING
$^   Xtratext, 5, SEV_WARNING
$^   SeqPosComma, 6, SEV_ERROR
$^   Pos, 7, SEV_WARNING
$^   EmptyNote, 8, SEV_WARNING
$^   NoteEmbeddedQual, 9, SEV_WARNING
$^   EmbeddedQual, 10, SEV_WARNING
$^   AA, 11, SEV_WARNING
$^   Seq, 12, SEV_WARNING
$^   BadECnum, 13, SEV_WARNING
$^   Cons_splice, 14, SEV_WARNING
