.\"     Title: \fBmake_win_src_distribution\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 07/04/2007
.\"    Manual: MySQL Database System
.\"    Source: MySQL 5.0
.\"
.TH "\fBMAKE_WIN_SRC_DIST" "1" "07/04/2007" "MySQL 5.0" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
make_win_src_distribution \- create source distribution for Windows
.SH "SYNOPSIS"
.HP 36
\fBmake_win_src_distribution [\fR\fB\fIoptions\fR\fR\fB]\fR
.SH "DESCRIPTION"
.PP
\fBmake_win_src_distribution\fR
creates a Windows source package to be used on Windows systems. It is used after you configure and build the source distribution on a Unix or Unix\-like system so that you have a server binary to work with. (See the instructions at
Section\ 4.14.6.4, \(lqCreating a Windows Source Package from the Latest Development Source\(rq.)
.PP
Invoke
\fBmake_win_src_distribution\fR
like this from the top\-level directory of a MySQL source distribution:
.sp
.RS 3n
.nf
shell> \fBmake_win_src_distribution [\fR\fB\fIoptions\fR\fR\fB]\fR
.fi
.RE
.PP
\fBmake_win_src_distribution\fR
understands the following options:
.TP 3n
\(bu
\fB\-\-help\fR
.sp
Display a help message and exit.
.TP 3n
\(bu
\fB\-\-debug\fR
.sp
Print information about script operations; do not create a package.
.TP 3n
\(bu
\fB\-\-tmp\fR
.sp
Specify the temporary location.
.TP 3n
\(bu
\fB\-\-suffix\fR
.sp
The suffix name for the package.
.TP 3n
\(bu
\fB\-\-dirname\fR
.sp
Directory name to copy files (intermediate).
.TP 3n
\(bu
\fB\-\-silent\fR
.sp
Do not print verbose list of files processed.
.TP 3n
\(bu
\fB\-\-tar\fR
.sp
Create a
\fItar.gz\fR
package instead of a
\fI.zip\fR
package.
.sp
By default,
\fBmake_win_src_distribution\fR
creates a Zip\-format archive with the name
\fImysql\-\fR\fI\fIVERSION\fR\fR\fI\-win\-src.zip\fR, where
\fIVERSION\fR
represents the version of your MySQL source tree.
.SH "COPYRIGHT"
.PP
Copyright 1997\-2007 MySQL AB
.PP
This documentation is NOT distributed under a GPL license. Use of this documentation is subject to the following terms: You may create a printed copy of this documentation solely for your own personal use. Conversion to other formats is allowed as long as the actual content is not altered or edited in any way. You shall not publish or distribute this documentation in any form or on any media, except if you distribute the documentation in a manner similar to how MySQL disseminates it (that is, electronically for download on a Web site with the software) or on a CD\-ROM or similar medium, provided however that the documentation is disseminated together with the software on the same medium. Any other use, such as any dissemination of printed copies or use of this documentation, in whole or in part, in another publication, requires the prior written consent from an authorized representative of MySQL AB. MySQL AB reserves any and all rights to this documentation not expressly granted above.
.PP
Please email
<docs@mysql.com>
for more information.
.SH "SEE ALSO"
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
This software comes with no warranty.
