.\"     Title: \fBmysql_explain_log\fR
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 11/02/2006
.\"    Manual: MySQL Database System
.\"    Source: MySQL 4.1
.\"
.TH "\fBMYSQL_EXPLAIN_LOG" "1" "11/02/2006" "MySQL 4.1" "MySQL Database System"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mysql_explain_log \- use EXPLAIN on statements in query log
.SH "SYNOPSIS"
.HP 39
\fBmysql_explain_log [\fR\fB\fIoptions\fR\fR\fB] < \fR\fB\fIlog_file\fR\fR
.SH "DESCRIPTION"
.PP
\fBmysql_explain_log\fR
reads its standard input for query log contents. It uses
EXPLAIN
to analyze
SELECT
statements found in the input.
UPDATE
statements are rewritten to
SELECT
statements and also analyzed with
EXPLAIN.
\fBmysql_explain_log\fR
then displays a summary of its results.
.PP
The results may assist you in determining which queries result in table scans and where it would be beneficial to add indexes to your tables.
.PP
Invoke
\fBmysql_explain_log\fR
like this, where
\fIlog_file\fR
contains all or part of a MySQL query log:
.sp
.RS 3n
.nf
shell> \fBmysql_explain_log [\fR\fB\fIoptions\fR\fR\fB] < \fR\fB\fIlog_file\fR\fR
.fi
.RE
.PP
\fBmysql_explain_log\fR
understands the following options:
.TP 3n
\(bu
\fB\-\-date=\fR\fB\fIYYMMDD\fR\fR,
\fB\-d \fR\fB\fIYYMMDD\fR\fR
.sp
Select entries from the log only for the given date.
.TP 3n
\(bu
\fB\-\-host=\fR\fB\fIhost_name\fR\fR,
\fB\-h \fR\fB\fIhost_name\fR\fR
.sp
Connect to the MySQL server on the given host.
.TP 3n
\(bu
\fB\-\-password=\fR\fB\fIpassword\fR\fR,
\fB\-p\fR\fB\fIpassword\fR\fR
.sp
The password to use when connecting to the server.
.sp
Specifying a password on the command line should be considered insecure. See
Section\ 7.6, \(lqKeeping Your Password Secure\(rq.
.TP 3n
\(bu
\fB\-\-printerror=1\fR,
\fB\-e 1\fR
.sp
Enable error output.
.TP 3n
\(bu
\fB\-\-socket=\fR\fB\fIpath\fR\fR,
\fB\-S \fR\fB\fIpath\fR\fR
.sp
For connections to
localhost, the Unix socket file to use, or, on Windows, the name of the named pipe to use.
.TP 3n
\(bu
\fB\-\-user=\fR\fB\fIuser_name\fR\fR,
\fB\-u \fR\fB\fIuser_name\fR\fR
.sp
The MySQL username to use when connecting to the server.
.SH "COPYRIGHT"
.PP
Copyright 1997\-2006 MySQL AB
.PP
This documentation is NOT distributed under a GPL license. Use of this documentation is subject to the following terms: You may create a printed copy of this documentation solely for your own personal use. Conversion to other formats is allowed as long as the actual content is not altered or edited in any way. You shall not publish or distribute this documentation in any form or on any media, except if you distribute the documentation in a manner similar to how MySQL disseminates it (that is, electronically for download on a Web site with the software) or on a CD\-ROM or similar medium, provided however that the documentation is disseminated together with the software on the same medium. Any other use, such as any dissemination of printed copies or use of this documentation, in whole or in part, in another publication, requires the prior written consent from an authorized representative of MySQL AB. MySQL AB reserves any and all rights to this documentation not expressly granted above.
.PP
Please email
<docs@mysql.com>
for more information.
.SH "SEE ALSO"
isamchk(1),
isamlog(1),
msql2mysql(1),
myisam_ftdump(1),
myisamchk(1),
myisamlog(1),
myisampack(1),
mysql(1),
mysql.server(1),
mysql_config(1),
mysql_fix_privilege_tables(1),
mysql_zap(1),
mysqlaccess(1),
mysqladmin(1),
mysqlbinlog(1),
mysqlcheck(1),
mysqld(1),
mysqld(8),
mysqld_multi(1),
mysqld_safe(1),
mysqldump(1),
mysqlhotcopy(1),
mysqlimport(1),
mysqlshow(1),
pack_isam(1),
perror(1),
replace(1),
safe_mysqld(1)
.P
For more information, please refer to the MySQL Reference Manual,
which may already be installed locally and which is also available
online at http://dev.mysql.com/doc/.
.SH AUTHOR
MySQL AB (http://www.mysql.com/).
This software comes with no warranty.
