#!/bin/sh

#Darwin BuildTarball script

PLAT=`uname`

echo removing StreamingProxy-4.1.2-MacOSX.tar.gz
if rm -f StreamingProxy-4.1.2-MacOSX.tar.gz; 
then :
fi

echo removing StreamingProxy-4.1.2-MacOSX
if rm -rf StreamingProxy-4.1.2-MacOSX; 
then :
fi

#cvs -q up
./Buildit
cp build/StreamingProxy StreamingProxy.tproj/

./DSS_MakeProxyRoot StreamingProxy-4.1.2-MacOSX
tar cvf StreamingProxy-4.1.2-MacOSX.tar StreamingProxy-4.1.2-MacOSX
gzip StreamingProxy-4.1.2-MacOSX.tar

echo Done!
