/* This file is automatically generated from wc-metadata.sql.
 * Do not edit this file -- edit the source and rerun gen-make.py */

#define WC_METADATA_SQL \
  "CREATE TABLE REPOSITORY ("\
  "  id INTEGER PRIMARY KEY AUTOINCREMENT,"\
  "  root  TEXT NOT NULL,"\
  "  uuid  TEXT NOT NULL"\
  "  );"\
  "CREATE TABLE WCROOT ("\
  "  id  INTEGER PRIMARY KEY AUTOINCREMENT,"\
  "  local_abspath  TEXT"\
  "  );"\
  "CREATE UNIQUE INDEX I_LOCAL_ABSPATH ON WCROOT (local_abspath);"\
  "CREATE TABLE BASE_NODE ("\
  "  id  INTEGER PRIMARY KEY AUTOINCREMENT,"\
  "  wc_id  INTEGER,"\
  "  local_relpath  TEXT NOT NULL,"\
  "  repos_id  INTEGER,"\
  "  repos_relpath  TEXT,"\
  "  parent_id  INTEGER,"\
  "  revnum  INTEGER NOT NULL,"\
  "  kind  TEXT NOT NULL,"\
  "  checksum  TEXT,"\
  "  translated_size  INTEGER,"\
  "  changed_rev  INTEGER NOT NULL,"\
  "  changed_date  INTEGER NOT NULL,  "\
  "  changed_author  TEXT NOT NULL,"\
  "  depth  TEXT,"\
  "  last_mod_time  INTEGER,  "\
  "  properties  BLOB NOT NULL,"\
  "  incomplete_children  INTEGER"\
  "  );"\
  "CREATE UNIQUE INDEX I_PATH ON BASE_NODE (wc_id, local_relpath);"\
  "CREATE INDEX I_PARENT ON BASE_NODE (parent_id);"\
  "CREATE TABLE PRISTINE ("\
  "  checksum  TEXT NOT NULL PRIMARY KEY,"\
  "  compression  INTEGER,"\
  "  size  INTEGER,"\
  "  refcount  INTEGER NOT NULL"\
  "  );"\
  "CREATE TABLE WORKING_NODE ("\
  "  id  INTEGER PRIMARY KEY AUTOINCREMENT, "\
  "  wc_id  INTEGER,"\
  "  local_relpath  TEXT NOT NULL,"\
  "  parent_relpath  TEXT NOT NULL,"\
  "  kind  TEXT NOT NULL,"\
  "  copyfrom_repos_id  INTEGER,"\
  "  copyfrom_repos_path  TEXT,"\
  "  copyfrom_revnum  INTEGER,"\
  "  moved_from  TEXT,"\
  "  moved_to  TEXT,"\
  "  checksum  TEXT,"\
  "  translated_size  INTEGER,"\
  "  changed_rev  INTEGER,"\
  "  changed_date  INTEGER,  "\
  "  changed_author  TEXT,"\
  "  depth  TEXT,"\
  "  last_mod_time  INTEGER,  "\
  "  properties  BLOB NOT NULL,"\
  "  changelist_id  INTEGER,"\
  "  tree_conflict_data  TEXT"\
  "  );"\
  "CREATE UNIQUE INDEX I_WORKING_PATH ON WORKING_NODE (wc_id, local_relpath);"\
  "CREATE INDEX I_WORKING_PARENT ON WORKING_NODE (parent_relpath);"\
  "CREATE TABLE ACTUAL_NODE ("\
  "  id  INTEGER PRIMARY KEY AUTOINCREMENT,"\
  "  wc_id  INTEGER,"\
  "  local_relpath  TEXT NOT NULL,"\
  "  properties  BLOB,"\
  "  conflict_old  TEXT,"\
  "  conflict_new  TEXT,"\
  "  conflict_working  TEXT,"\
  "  prop_reject  TEXT,  "\
  "  changelist_id  INTEGER"\
  "  );"\
  "CREATE TABLE CHANGELIST ("\
  "  id  INTEGER PRIMARY KEY AUTOINCREMENT,"\
  "  wc_id  INTEGER,"\
  "  name  TEXT NOT NULL"\
  "  );"\
  "CREATE UNIQUE INDEX I_CHANGELIST ON CHANGELIST (wc_id, name);"\
  "CREATE UNIQUE INDEX I_CL_LIST ON CHANGELIST (wc_id);"\
  "CREATE TABLE LOCK ("\
  "  url  TEXT NOT NULL PRIMARY KEY,"\
  "  lock_token  TEXT NOT NULL,"\
  "  lock_owner  TEXT,"\
  "  lock_comment  TEXT,"\
  "  lock_date  INTEGER   "\
  "  );"\
  ""
