/* This file is automatically generated from rep-cache-db.sql.
 * Do not edit this file -- edit the source and rerun gen-make.py */

#define REP_CACHE_DB_SQL \
  "pragma auto_vacuum = 1;"\
  "create table rep_cache (hash text not null primary key,"\
  "                        revision integer not null,"\
  "                        offset integer not null,"\
  "                        size integer not null,"\
  "                        expanded_size integer not null);"\
  ""
