#!/bin/sh

. /etc/rc.common

/bin/rm -f /Library/QuickTimeStreaming/Playlists/*/*.pid
/bin/rm -f /Library/QuickTimeStreaming/Playlists/*/*.current
/bin/rm -f /Library/QuickTimeStreaming/Playlists/*/*.upcoming

if [ "${QTSSRUNSERVER}" = "-YES-" ]; then
    ConsoleMessage "Starting QuickTime Streaming Services"

    /usr/sbin/QuickTimeStreamingServer
fi

if [ "${QTSSWEBADMIN}" = "-YES-" ]; then
    ConsoleMessage "Starting QuickTime Streaming Services"

    /usr/sbin/streamingadminserver.pl
fi
