#!perl -wl
use strict;
use Mac::Glue ':glue';

my $g = new Mac::Glue 'Finder';
my $sd = $g->prop('Startup Disk');
my $all = $g->obj(disks => gAll);

print "Startup disk:\n  ", $sd->prop('name')->get;

print "\nAll disks:\n",
    map {"  $_\n"} sort $all->prop('name')->get;

__END__
