#!perl -wl

use Mac::Glue;

$s = new Mac::Glue 'Sherlock';
$s->activate;

@results = $s->search_internet([qw[AltaVista HotBot Lycos]], For => 'Mac::Glue');
warn $^E if $^E;

# unpack HotBot links
for (@results) {
    if (s|^http://www.hotbot.com/.*target=([^&]+).*$|$1|) {
        s/%([A-Fa-f0-9]{2})/chr hex $1/ge;
    }
}

print @results ? join("\n", sort @results) : "No matches found.";

$s->quit;

__END__
