#!perl -w
use strict;
use File::Spec::Functions;
use Mac::Glue ':all';
use Mac::Files;
use Mac::InternetConfig;

my $file = catfile(
	FindFolder(kOnSystemDisk, kDesktopFolderType),
	"projects-1.html"
);
die "'$file' already exists.\n" if -e $file;
my $map  = $InternetConfigMap{$file};

my $url = new Mac::Glue 'URL Access Scripting';
$url->activate;
$url->download(
	'http://projects.pudge.net/',
	to => $file, progress => 1
);
die $MacError if $^E;
$url->quit;

if ($map && ref $map && $map->file_creator && $map->file_type) {
	MacPerl::SetFileInfo($map->file_creator, $map->file_type, $file);
}
