.TH ASNDHUFF 1 2002-08-30 NCBI "NCBI Tools User's Manual"
.SH NAME
asndhuff \- decompress compressed ASN.1 (CASN) files
.SH SYNOPSIS
.B asndhuff
[\|\fB\-\fP\|]
\fB\-i\fP\ \fIfilename\fP
[\|\fB\-o\fP\ \fIfilename\fP\|]
.SH DESCRIPTION
\fBasndhuff\fP decompresses compressed ASN.1 (CASN) files.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-i\fP\ \fIfilename\fP
Read input from \fIfilename\fP
.TP
\fB\-o\fP\ \fIfilename\fP
Write output to \fIfilename\fP (stdout by default)
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.BR asn2asn (1),
.BR asn2ff (1),
.BR asn2gb (1),
.BR asn2xml (1)
