.TH DDV 1 2001-10-05 NCBI "NCBI Tools User's Manual"
.SH NAME
ddv \- DeuxD-Viewer for multiple sequence alignment
.SH SYNOPSIS
.B ddv
[\|\fB\-\fP\|]
[\|\fB\-e\ F\fP\|]
[\|\fB\-g\ F\fP\|]
.SH DESCRIPTION
\fBddv\fP is a standalone graphical viewer for multiple sequence alignment.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-e\ F\fP
Do not allow edits
.TP
\fB\-g\ F\fP
Do not allow gaps
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.ad l
.BR Cn3D (1),
.BR udv (1),
<http://www.ncbi.nlm.nih.gov/Structure/CN3D/ddv.shtml>
