.TH FINDSPL 1 2001-10-05 NCBI "NCBI Tools User's Manual"
.SH NAME
findspl \- find protein splice sites
.SH SYNOPSIS
.B findspl
[\|\fB\-\fP\|]
[\|\fB\-g\fP\ \fIN\fP\|]
[\|\fB\-i\fP\ \fIfilename\fP\|]
[\|\fB\-o\fP\ \fIfilename\fP\|]
.SH DESCRIPTION
\fBfindspl\fP is a simple tool to find protein splice sites.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-g\fP\ \fIN\fP
GI number of protein
.TP
\fB\-i\fP\ \fIfilename\fP
Input file containing protein GIs (default is stdin)
.TP
\fB\-o\fP\ \fIfilename\fP
Output file (default is stdout)
.SH AUTHOR
The National Center for Biotechnology Information.
