.TH GETMESH 1 2001-10-05 NCBI "NCBI Tools User's Manual"
.SH NAME
getmesh \- get MeSH terms from a Medline entry
.SH SYNOPSIS
.B getmesh
[\|\fB\-\fP\|]
[\|\fB\-b\fP\|]
\fB\-i\fP\ \fIfilename\fP
\fB\-o\fP\ \fIfilename\fP
.SH DESCRIPTION
\fBgetmesh\fP is a simple program to get mesh terms from a Medline entry.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-b\fP
(ASN.1) input data is binary rather than ASCII text
.TP
\fB\-i\fP\ \fIfilename\fP
Input data
.TP
\fB\-o\fP\ \fIfilename\fP
Output list
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.BR getpub (1)
