.TH GIL2BIN 1 2003-04-27 NCBI "NCBI Tools User's Manual"
.SH NAME
gil2bin \- convert GenInfo integrated IDs to or from binary
.SH SYNOPSIS
.B gil2bin
[\|\fB\-\fP\|]
\fB\-i\fP\ \fIfilename\fP
\fB\-o\fP\ \fIfilename\fP
[\|\fB\-r\fP\|]
.SH DESCRIPTION
\fBgil2bin\fP converts a list of GenInfo integrated IDs (GIs) from
text to binary, or vice versa.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-i\fP\ \fIfilename\fP
Read input from \fIfilename\fP
.TP
\fB\-o\fP\ \fIfilename\fP
Write output to \fIfilename\fP
.TP
\fB\-r\fP
Reverse mode (binary to text)
.SH AUTHOR
The National Center for Biotechnology Information.
