.TH NENTREZ 1 2001-11-21 NCBI "NCBI Tools User's Manual"
.SH NAME
Nentrez \- a graphical client for the NCBI Entrez retrieval system
.SH SYNOPSIS
.B Nentrez
.SH DESCRIPTION
\fBNentrez\fP (Network Entrez) is a TCP/IP-based client-server version
of WWW Entrez. This means it makes a direct connection with the NCBI
databases over the Internet to retrieve its data. The data comes in a
binary form taking up less network bandwidth during transfer.
.SH OPTIONS
None.
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.ad l
.BR entrez2 (1),
.BR netentcf (1),
<http://www.ncbi.nlm.nih.gov/Entrez/Network/nentrez.overview.html>
