.TH NETENTCF 1 2001-10-05 NCBI "NCBI Tools User's Manual"
.SH NAME
netentcf \- change Entrez network configuration
.SH SYNOPSIS
.B netentcf
.SH DESCRIPTION
\fBnetentcf\fP lets you configure Network Entrez's firewall and proxy
settings.
.SH OPTIONS
None.
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.ad l
.BR Nentrez (1),
<http://www.ncbi.nlm.nih.gov/Entrez/Network/nentrez.overview.html>
