.TH UDV 1 2001-10-05 NCBI "NCBI Tools User's Manual"
.SH NAME
udv \- OneD-Viewer for biological sequences
.SH SYNOPSIS
.B udv
.SH DESCRIPTION
\fBudv\fP is a standalone viewer for biological sequences.
.SH OPTIONS
None.
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.ad l
.BR Cn3D (1),
.BR ddv (1),
<http://www.ncbi.nlm.nih.gov/Structure/CN3D/udv.shtml>
