MODULE medarch
$$ REFERENCE, 1
$^   MuidNotFound, 1, SEV_WARNING
$^   SuccessfulMuidLookup, 2, SEV_INFO
$^   OldInPress, 3, SEV_WARNING
$^   No_reference, 4, SEV_WARNING
$^   Multiple_ref, 5, SEV_WARNING
$^   Multiple_muid, 6, SEV_WARNING
$^   MedlineMatchIgnored, 7, SEV_ERROR
$^   MuidMissmatch, 8, SEV_WARNING
$^   NoConsortAuthors, 9, SEV_WARNING
$^   DiffConsortAuthors, 10, SEV_WARNING
$^   PmidMismatch, 11, SEV_WARNING
$^   Multiple_pmid, 12, SEV_WARNING
$^   FailedToGetPub, 13, SEV_ERROR
$^   MedArchMatchIgnored, 14, SEV_ERROR
$^   SuccessfulPmidLookup, 15, SEV_INFO
$^   PmidNotFound, 16, SEV_WARNING
$$ PRINT, 2
$^   Failed, 1, SEV_WARNING
