#!/bin/csh -f
#
# make a symbolic link if the target is absent
#
# $Id: ln-if-absent,v 1.4 2000/06/06 23:07:33 beloslyu Exp $
#

set path=(/usr/bin /bin)

if ($#argv < 2) then
	echo "Usage: $0 source_file... target"
	exit 1
endif

@ count=$#argv
set target=$argv[$count]
@ count--
set list=($argv[-$count])
set final=()

if (-d $target) then
	foreach i ($list)	
		if (! -r $target/$i:t) set final=($final $i)
	end
else
	if ($#argv != 2) then
		echo target argument should not be a directory
		exit 1
	endif
	if (! -r "$1") exit 1
	if (! -r "$2") ln -sf "$1" "$2" 
	exit 0
endif

if ( $#final == 1) then
	if (! -r "$final") exit 1
	ln -s $final $target
	exit 0
endif

if ($#final != 0) then
	ln -s $final $target
endif

exit 0
